import os
import json
from datetime import datetime
from pathlib import Path

# Configuration
GOALCAST_ROOT = Path(__file__).resolve().parent.parent
PREDICTIONS_DIR = GOALCAST_ROOT / "data" / "predictions"
BACKTESTS_DIR = GOALCAST_ROOT / "data" / "backtests"
RESULTS_DIR = GOALCAST_ROOT / "data" / "results"
REPORTS_DIR = GOALCAST_ROOT / "data" / "reports"

def generate_dashboard():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    today_str = datetime.now().strftime("%Y-%m-%d")
    
    # 1. Collect Prediction Stats
    pred_files = list(PREDICTIONS_DIR.glob(f"{today_str}_*.json"))
    total_preds = 0
    for pf in pred_files:
        with open(pf, 'r') as f:
            data = json.load(f)
            if "comparison" in data:
                total_preds += 2
            else:
                total_preds += 1
                
    # 2. Collect Result Stats (Pending matches)
    result_files = list(RESULTS_DIR.glob(f"{today_str}_*.json"))
    settled_matches = len(result_files)
    
    # 3. Get Latest Backtest Summary
    latest_backtest_file = BACKTESTS_DIR / f"backtest_{today_str}_to_{today_str}.json"
    roi = "0.0%"
    hit_rate = "0.0%"
    if latest_backtest_file.exists():
        with open(latest_backtest_file, 'r') as f:
            bt_data = json.load(f)
            roi = f"{bt_data.get('metrics', {}).get('roi_pct', 0)}%"
            hit_rate = f"{bt_data.get('metrics', {}).get('hit_rate_pct', 0)}%"

    # 4. Construct Markdown
    md_content = f"""# Goalcast Daily Quant Dashboard ({today_str})

## 📊 系统运行概览 (System Overview)
| 指标 | 当前数值 | 状态 |
| :--- | :--- | :--- |
| **今日预测总数** | {total_preds} | ✅ 运行中 |
| **已结算场次** | {settled_matches} | ⏳ 等待 Cron 复盘 |
| **当前 ROI** | {roi} | - |
| **当前命中率** | {hit_rate} | - |

## 🔍 今日预测详情 (Today's Predictions)
"""
    
    # Add prediction links
    for pf in sorted(PREDICTIONS_DIR.glob(f"{today_str}_*.md")):
        with open(pf, 'r') as f:
            lines = f.readlines()
            match_name = pf.stem.replace("_compare", "").replace("_", " ").title()
            for line in lines:
                clean_line = line.strip().replace("*", "")
                if clean_line.startswith("赛事") and ":" in clean_line:
                    match_name = clean_line.split(":", 1)[1].strip()
                    break
        md_content += f"- [{match_name}](data/predictions/{pf.name})\n"

    md_content += f"""
## 📈 最新回测简报 (Latest Backtest)
- [查看详细回测报告](data/backtests/backtest_{today_str}_to_{today_str}.md)

## 🛠 系统健康度 (System Health)
- **MCP Server**: ✅ Connected
- **Cron Jobs**: ✅ Active (Review Every 6h)
- **Data Persistence**: ✅ Functional

---
*Generated by Goalcast Quant Dashboard System*
"""

    dashboard_path = REPORTS_DIR / f"dashboard_{today_str}.md"
    with open(dashboard_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    
    print(f"Dashboard generated: {dashboard_path}")

if __name__ == "__main__":
    generate_dashboard()
